# Generated by Django 5.1.1 on 2024-10-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0002_remove_privateclass_owners_remove_publicclass_owners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateclass',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
