# Generated by Django 5.1.1 on 2024-10-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0003_privateclass_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateclass',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicclass',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
