# Generated by Django 5.1.1 on 2024-10-02 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answer_app', '0001_initial'),
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileanswer',
            name='group_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.grouptask'),
        ),
        migrations.AddField(
            model_name='fileanswer',
            name='single_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.singletask'),
        ),
        migrations.AddField(
            model_name='judgeanswer',
            name='group_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.grouptask'),
        ),
        migrations.AddField(
            model_name='judgeanswer',
            name='single_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.singletask'),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='group_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.grouptask'),
        ),
        migrations.AddField(
            model_name='textanswer',
            name='single_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.singletask'),
        ),
    ]
