# Generated by Django 5.1.1 on 2024-10-02 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_app', '0001_initial'),
        ('answer_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreBarGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_result', models.FloatField()),
                ('clean_code', models.FloatField()),
                ('teamwork', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ScoreBarSingle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_result', models.FloatField()),
                ('clean_code', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('first_deadline', models.DateField()),
                ('second_deadline', models.DateField(blank=True, null=True)),
                ('submit_limit', models.IntegerField(blank=True, null=True)),
                ('score_bar', models.IntegerField(blank=True, null=True)),
                ('question_bank', models.BooleanField()),
                ('file_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answer_app.fileanswer')),
                ('judge_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answer_app.judgeanswer')),
                ('text_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answer_app.textanswer')),
            ],
        ),
        migrations.CreateModel(
            name='SingleTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('result', models.FloatField()),
                ('score_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.scorebarsingle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.account')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.task')),
            ],
        ),
        migrations.CreateModel(
            name='GroupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('result', models.FloatField()),
                ('users', models.ManyToManyField(to='account_app.account')),
                ('score_bar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task_app.scorebargroup')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_app.task')),
            ],
        ),
    ]
