# Generated by Django 5.1.1 on 2024-10-07 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_app', '0002_initial'),
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer_type',
            field=models.CharField(blank=True, choices=[('file', 'File Answer'), ('judge', 'Judge Answer'), ('text', 'Text Answer')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='file_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='answer_app.fileanswer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='judge_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='answer_app.judgeanswer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='text_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='answer_app.textanswer'),
        ),
    ]
