# Generated by Django 5.1.1 on 2024-10-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_grouptask_result_alter_singletask_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptask',
            name='class_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singletask',
            name='class_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
