# Generated by Django 5.1.1 on 2024-10-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_grouptask_class_id_singletask_class_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouptask',
            old_name='class_id',
            new_name='private_class_id',
        ),
        migrations.RenameField(
            model_name='singletask',
            old_name='class_id',
            new_name='private_class_id',
        ),
        migrations.AddField(
            model_name='grouptask',
            name='public_class_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='singletask',
            name='public_class_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
